-- Schemas / users for the synthetic warehouse
CREATE USER WH_RAW IDENTIFIED BY "demo" QUOTA UNLIMITED ON USERS;
CREATE USER WH_STG IDENTIFIED BY "demo" QUOTA UNLIMITED ON USERS;
CREATE USER WH_DW  IDENTIFIED BY "demo" QUOTA UNLIMITED ON USERS;
CREATE USER WH_RPT IDENTIFIED BY "demo" QUOTA UNLIMITED ON USERS;
CREATE USER WH_LEGACY IDENTIFIED BY "demo" QUOTA UNLIMITED ON USERS;
