"""Push a generated Dataform project to a GitHub repo.

The flow is intentionally minimal — git CLI in a temp dir, force-push so
re-runs always land cleanly. Auth is via a user-supplied PAT injected
into the remote URL. We never log or persist the token.
"""

from __future__ import annotations

import logging
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

import httpx

from app.services import gcs, transform_storage
from app.config import get_settings

log = logging.getLogger(__name__)


@dataclass
class PushResult:
    repo_url: str
    branch: str
    commit_sha: str
    commit_url: str
    files_pushed: int
    pull_request_url: str | None = None
    pull_request_number: int | None = None


class PushError(Exception):
    """Raised when any step of the git flow fails. Message is safe to
    surface to the user (token is redacted)."""


_REPO_URL_RE = re.compile(
    r"^https?://(?:www\.)?github\.com/(?P<owner>[\w.-]+)/(?P<repo>[\w.-]+?)(?:\.git)?/?$"
)


def push_to_github(
    run_id: str,
    repo_url: str,
    branch: str,
    commit_message: str,
    github_token: str,
    force: bool = True,
    as_pull_request: bool = False,
    pr_title: str = "",
    pr_body: str = "",
) -> PushResult:
    """Clone the run's transform output from GCS, push it to `repo_url`.

    When `as_pull_request` is True, push to a generated feature branch
    (`intelia-migration/<run-id-prefix>`) and open a PR via the GitHub
    REST API targeting `branch` as the base. Otherwise force-push directly
    to `branch`.

    Returns a PushResult with the commit SHA + viewable URLs.
    """
    m = _REPO_URL_RE.match(repo_url.strip())
    if not m:
        raise PushError(f"not a github.com URL: {repo_url}")
    owner, repo = m.group("owner"), m.group("repo")
    base_branch = branch
    head_branch = (
        f"intelia-migration/{run_id[:8]}" if as_pull_request else branch
    )

    files = transform_storage.list_files(run_id)
    if not files:
        raise PushError(f"no transform output for run {run_id} — generate it first")

    # Build an authenticated remote URL. The token is URL-encoded in case
    # it contains characters git's URL parser would treat specially.
    auth_url = f"https://x-access-token:{quote(github_token, safe='')}@github.com/{owner}/{repo}.git"

    settings = get_settings()
    bucket = settings.results_bucket
    prefix = f"runs/{run_id}/transform"

    tmp = Path(tempfile.mkdtemp(prefix="dataform-push-"))
    try:
        # 1. Initialise local repo on the head branch (the branch we'll
        # actually push to — same as base for direct pushes, a feature
        # branch when opening a PR).
        _git(tmp, "init", "-b", head_branch)
        _git(tmp, "config", "user.name", "intelia migration agent")
        _git(tmp, "config", "user.email", "noreply@intelia.com.au")

        # 2. Pull every file from GCS into the working dir.
        files_pushed = 0
        for path in files:
            content = gcs.read_text(bucket, f"{prefix}/{path}")
            target = tmp / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            files_pushed += 1
        # Originals too — useful for code review on the PR.
        for orig in gcs.list_blobs(bucket, f"{prefix}/_originals/"):
            rel = orig.removeprefix(f"{prefix}/")
            content = gcs.read_text(bucket, orig)
            target = tmp / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            files_pushed += 1

        # 3. Commit
        _git(tmp, "add", ".")
        try:
            _git(tmp, "commit", "-m", commit_message)
        except PushError as e:
            # Empty diff is OK if user is force-pushing identical content.
            if "nothing to commit" not in str(e).lower():
                raise

        # 4. Push
        _git(tmp, "remote", "add", "origin", auth_url)
        push_args = ["push", "--force-with-lease" if not force else "--force",
                     "-u", "origin", head_branch]
        _git(tmp, *push_args)

        sha = _git(tmp, "rev-parse", "HEAD").strip()
        commit_url = f"https://github.com/{owner}/{repo}/commit/{sha}"

        # 5. Open a PR (if requested). Errors here are non-fatal — the
        # push itself succeeded, the user can open the PR manually.
        pr_url = None
        pr_number = None
        if as_pull_request and head_branch != base_branch:
            try:
                pr_url, pr_number = _open_pull_request(
                    owner, repo, github_token,
                    head=head_branch, base=base_branch,
                    title=pr_title or commit_message,
                    body=pr_body or "Generated by intelia Insignia migration agents.",
                )
            except PushError as e:
                log.warning("PR open failed but push succeeded: %s", e)
                pr_url = None

        return PushResult(
            repo_url=f"https://github.com/{owner}/{repo}",
            branch=head_branch,
            commit_sha=sha,
            commit_url=commit_url,
            files_pushed=files_pushed,
            pull_request_url=pr_url,
            pull_request_number=pr_number,
        )
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _open_pull_request(
    owner: str, repo: str, token: str,
    head: str, base: str, title: str, body: str,
) -> tuple[str, int]:
    """Open a PR via the GitHub REST API. Returns (html_url, pr_number)."""
    try:
        r = httpx.post(
            f"https://api.github.com/repos/{owner}/{repo}/pulls",
            json={"title": title[:250], "body": body, "head": head, "base": base},
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            timeout=30,
        )
    except httpx.HTTPError as e:
        raise PushError(f"PR API call failed: {e}")
    if r.status_code == 422 and "pull request already exists" in (r.text or "").lower():
        # Find the existing PR for this head branch.
        existing = httpx.get(
            f"https://api.github.com/repos/{owner}/{repo}/pulls",
            params={"head": f"{owner}:{head}", "state": "open"},
            headers={"Authorization": f"Bearer {token}"},
            timeout=30,
        )
        if existing.status_code == 200 and existing.json():
            pr = existing.json()[0]
            return pr["html_url"], pr["number"]
    if r.status_code >= 300:
        raise PushError(f"PR API {r.status_code}: {r.text[:300]}")
    pr = r.json()
    return pr["html_url"], pr["number"]


def _git(cwd: Path, *args: str) -> str:
    """Run git in `cwd`, return stdout. Redacts any embedded auth token
    from error messages so PATs never leak into logs or API responses.
    """
    result = subprocess.run(
        ["git", *args],
        cwd=str(cwd),
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0:
        msg = (result.stderr or result.stdout or "git failed").strip()
        # Strip any "x-access-token:<token>@github.com" pattern out of error text.
        msg = re.sub(r"x-access-token:[^@]+@", "x-access-token:***@", msg)
        raise PushError(f"git {args[0]}: {msg}")
    return result.stdout
