"""Orchestration agent — generates a GitHub Actions workflow that runs
`dataform compile` + scheduled `dataform run` against the SQLX project
the Transformation agent just produced.

Files emitted (added to the same Dataform project tree on GCS):
    .github/workflows/dataform.yaml

Skips silently when no transform output exists yet (depends on the
transform agent having run first).
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone

from app.agents.base import EmitFn, log_event
from app.config import get_settings
from app.models.run import AgentName, RunRequest, StreamEvent
from app.services import gcs, transform_storage

log = logging.getLogger(__name__)

last_result: dict | None = None


_WORKFLOW_YAML = """\
# GitHub Actions workflow for the Dataform project.
# Generated by intelia Lineage & Usage Agents (orchestration).
#
# - Compile-on-push validates SQLX on every commit (catches ref errors,
#   syntax breakage) without touching BigQuery.
# - Run-on-schedule (daily 02:00 UTC) materialises tables. Configure
#   GCP authentication via Workload Identity Federation: set the repo
#   secrets WIF_PROVIDER and WIF_SERVICE_ACCOUNT.
# - Manual runs available via the "Run workflow" button (workflow_dispatch).

name: Dataform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # required for Workload Identity Federation

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dataform CLI
        run: npm install -g @dataform/cli @dataform/core
      - name: Compile
        run: dataform compile

  run:
    name: Run
    needs: compile
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Dataform CLI
        run: npm install -g @dataform/cli @dataform/core
      - name: Run
        run: dataform run
"""


async def run(req: RunRequest, results, emit: EmitFn, run_id: str) -> None:
    """Generate workflow files and add them to the project on GCS."""
    global last_result
    last_result = None

    # Skip if no transform output exists for this run.
    manifest = transform_storage.read_manifest(run_id)
    if manifest is None:
        await log_event(emit, AgentName.ORCHESTRATION,
                        "skipped: no transform output yet — run the transform agent first")
        return

    settings = get_settings()
    bucket = settings.results_bucket
    prefix = f"runs/{run_id}/transform"

    files_added: list[str] = [".github/workflows/dataform.yaml"]
    gcs.write_text(
        bucket,
        f"{prefix}/.github/workflows/dataform.yaml",
        _WORKFLOW_YAML,
        content_type="application/x-yaml",
    )
    await log_event(emit, AgentName.ORCHESTRATION,
                    "wrote .github/workflows/dataform.yaml — compile-on-push + scheduled run")

    # Append the new files to the manifest so the UI shows them in the
    # tree without needing to re-walk GCS.
    new_files = sorted(set(manifest.files) | set(files_added))
    manifest.files = new_files
    manifest.file_meta = manifest.file_meta or {}
    for path in files_added:
        manifest.file_meta[path] = {
            "kind": "orchestration",
            "pipeline": "(orchestration)",
            "confidence": 100,
            "original_path": "",
        }
    manifest_dict = {
        **manifest.__dict__,
        "orchestration": {
            "kind": "github_actions",
            "files": files_added,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        },
    }
    gcs.write_json(bucket, f"{prefix}/_manifest.json", json.dumps(manifest_dict, indent=2))

    last_result = {"workflow": "github_actions", "files": files_added}
    await emit(StreamEvent(
        event="result",
        agent=AgentName.ORCHESTRATION,
        data={"workflow": "github_actions", "files_added": len(files_added)},
    ))
